### PR TITLE
Port ssh_authorize_key definition to a resource

### PR DESCRIPTION
**Pull request by bmhughes**
### Description

ssh_authorize_key has been ported to a resource so it can be easily subscribed to/nofity other resource when the key content is updated

### Issues Resolved

[List any existing issues this PR resolves]

### Contribution Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README and metadata if applicable.

See [CONTRIBUTING.md](https://github.com/zuazo/ssh_authorized_keys-cookbook/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by foobarbam** [comment]
Any chance to get this merged?  It's been here for almost a year.  Has this cookbook been abandoned?

**Comment by bmhughes** [comment]
There's not been any activity in any of @zuazo 's repos so I'm thinking of forking this work and releasing it as a new cookbook as it doesn't look like it will be merged any time soon.

**Comment by axelrtgs** [comment]
@zuazo I was wondering if this could be merged it would definitely bring this up to more recent chef best practices and support newer chef features/clients.

**Comment by bmhughes** [comment]
I fear the worst with the complete lack of activity on zuazo's repos so I'm going to fork this and push it to the supermarket under an altered name as soon as I get the chance to revisit. Hopefully in the next couple of weeks.

**Comment by zuazo** [comment]
Please, excuse my absence. I am in the process of merging these changes together with #16, and updating the cookbook.

**Comment by zuazo** [comment]
Released in [`1.0.0`](https://github.com/zuazo/ssh_authorized_keys-cookbook/releases/tag/1.0.0)

**Pull request merged**
