### PR TITLE
Uses gid from getpwnam()

### PR DESCRIPTION
**Pull request by ongmingyang**
I was trying to get this to work on my environment, but it was failing because my default group was not my user.

### CODE REVIEW

**Comment by zuazo** [comment]
Hi @ongmingyang,

Thanks for your PR. Please, could you fix the tests?

**Comment by ongmingyang** [comment]
I can't get the tests to run on my local environment as of now, due to dependency issues... but I'll see if I can get it to work.

**Comment by zuazo** [comment]
OK. Thanks @ongmingyang 

No rush anyway. I will leave the issue open.

**Comment by ongmingyang** [comment]
Hmm, I'm baffled. Do you know why `getpwnam()` can't find the user in the test?

**Comment by zuazo** [comment]
Use `require` instead of `load` for `'etc'`.

Keep in mind that you are reading the group name at compile time and chef creates the user at converge time [in the `ssh_authorized_keys_test::default` recipe](https://github.com/onddo/ssh_authorized_keys-cookbook/blob/master/test/cookbooks/ssh_authorized_keys_test/recipes/default.rb#L66-L91) (More info about the chef run: http://docs.chef.io/chef_client.html#the-chef-client-title-run). You will need to catch the exception and use `user` in this case.

So this fix will only work for users that existed before running chef. I'm not sure this will fix your use case.

**Comment by ongmingyang** [comment]
Hmm ok that makes sense, it worked for my particular use case because I use a central directory service for my users. 

It would seem like a strange practice to me to set the default group as `user` if the user cannot be found. If the user's default group isn't itself, chances are the group `user` does not exist, and the block will fail when trying to set the group ownership of the file to a non existent group.

Is there a way to load `etc` and/or read the user at runtime? Clearly using `load` didn't work.

**Comment by ongmingyang** [comment]
Hi @zuazo, thanks for all the help. I think the tests are passing now, could you check to see if everything is all good?

I also opened another PR for creating the `.ssh` directory recursively.

**Comment by zuazo** [comment]
太好了！谢谢！

**Comment by ongmingyang** [comment]
不客氣，謝謝妳的幫助：）

**Comment by zuazo** [comment]
不用谢 ；)

**Comment by zuazo** [comment]
Released in [`0.3.0`](https://github.com/zuazo/ssh_authorized_keys-cookbook/releases/tag/0.3.0).

**Pull request merged**
