### PR TITLE
Recursively create .ssh directory if it does not exist

### PR DESCRIPTION
**Pull request by ongmingyang**
I realized that the recipe also errors if my home directory is non-existent

### CODE REVIEW

**Comment by zuazo** [comment]
Thanks @ongmingyang! Please, can you update the tests in _spec/recipes/default_spec.rb_?

**Comment by ongmingyang** [comment]
@zuazo done!

**Comment by zuazo** [comment]
Sorry, a stupid detail: The `~/bob` format is wrong, `~bob` was right, wasn't it?

**Comment by ongmingyang** [comment]
Hmm, actually shouldn't it be `~/.ssh` instead? What does `~bob` refer to?

**Comment by zuazo** [comment]
`~bob` points to bob's home directory.

`~bob/.ssh` is the _.ssh_ directory in bob's home directory, usually `/home/bob/.ssh`.

**Comment by ongmingyang** [comment]
Hm, I've never seen that syntax being used before. I know `~` as an expansion of the home path though. Maybe this would be clearer?

```
-  it 'creates ~alice/.ssh directory' do
+  it 'creates alice ~/.ssh directory recursively' do
```

**Comment by ongmingyang** [comment]
Oh wow you're right it actually does resolve, I'll change it back then!

```
$ echo ~mingy
/export/home/mingy
```

**Comment by zuazo** [comment]
@ongmingyang, Thank you, I prefer my original syntax :-)

It is standardized by POSIX: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01

>  If none of the characters in the tilde-prefix are quoted, the characters in the tilde-prefix following the <tilde> are treated as a possible login name from the user database. [...] If the login name is null (that is, the tilde-prefix contains only the tilde), the tilde-prefix is replaced by the value of the variable HOME.

**Comment by ongmingyang** [comment]
Gotcha, I already changed it back ;)

**Comment by zuazo** [comment]
Thanks mingy!

**Comment by zuazo** [comment]
Released in [`0.3.0`](https://github.com/zuazo/ssh_authorized_keys-cookbook/releases/tag/0.3.0).

**Pull request merged**
